require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rails
  - rubocop-packaging

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false